sudo: false
language: ruby
cache: bundler
before_install:
- bundle -v
- rm -f Gemfile.lock
- gem update --system
- gem update bundler
- gem --version
- bundle -v
script: bundle exec rake validate lint spec
bundler_args: "--without system_tests"
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: othalla
  password:
    secure: "hMGXepwlmOzjtgkzFjLFWLftAEmijLXBvJ3hqvkjyRLWRkLh8jIU8O1MDZY0+JfZnqnXf6lP//tIqElHQxA7wpxG6YCLTkAiZ4VRW9QqmFwk1Rn6/IhAzoh+ZGDHl8SarwZqrwAqGyrYnEygEJM0t4M1tzxKJeRAWC8BOqL7NEIxyaq9h4SJMpDiBIuT7Mw48mPP2i9H2q3EENXK++DtgPLWE64Y0Qgl05PSZ294qjg7OtA2Lodtyo26JAF4/GxrKiAnmLxL0hYZOKhA9no9mygSm7yR+XQggmWyRD7ivLo+zWO63xBmxx/V7ejexsL9a7Ggf8GIl7FzTb56irVbzI5vJfp6l2lJOw2bzfesUDdqOgENBaebOjgwBlinnshkgf3+IaWYhOLQrhXKQOJRj8O+dXSCIGshxC2o+gOl9HVoeEsuwSZ4cE+CeMTTY2cEuPx6JQZaVFE5NvxcqKX86AByV1H3bY7S6Fu66J7Cx3dgPcFgiukOHs7yVm1nA9ghDclTlwBFfl63pbmCe+SEuLa92PDX1Fz+XorRVN9Ia8CE6rSMz10RiR+CbJVZEY/nIW/OE8BbAoBqqMHH+WwAKth+Z8LIGCbUPpKF557KAabufaIqwcMgBQatIN91v+gbhfy3eDiO1DqELbR6T+N0/t53mPE3rGyXMZt2DSXS8Ws="
  on:
    tags: true
    all_branches: true
    condition: "$FORGEDEPLOY = true"
